// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	domain "backend/domain"

	mock "github.com/stretchr/testify/mock"
)

// EmailServiceInterface is an autogenerated mock type for the EmailServiceInterface type
type EmailServiceInterface struct {
	mock.Mock
}

// SendResetPasswordEmail provides a mock function with given fields: email, resetToken
func (_m *EmailServiceInterface) SendResetPasswordEmail(email string, resetToken string) *domain.CustomError {
	ret := _m.Called(email, resetToken)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPasswordEmail")
	}

	var r0 *domain.CustomError
	if rf, ok := ret.Get(0).(func(string, string) *domain.CustomError); ok {
		r0 = rf(email, resetToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CustomError)
		}
	}

	return r0
}

// NewEmailServiceInterface creates a new instance of EmailServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailServiceInterface {
	mock := &EmailServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
