name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.5

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./backend  

    - name: Run Tests
      run: go test ./...
      working-directory: ./backend  